---
- hosts: all
  become: yes

  tasks:
    # - name: Set hostname
    #   hostname:
    #     name: dev_theta
        # use: systemd

    - name: Add the user "CTA"
      ansible.builtin.user:
        name: 'cta'
        comment: CTA
        password: $y$j9T$vm5bBbCpck0Z0xVGAwMYH.$xhjNRN2lu1rVRSqxirb/XfNbU.tYrgC6f6J.6OJLZ0B

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Upgrade packages (safely)
      apt:
        upgrade: safe

# Setup PXE booting
## Create folder for netboot
    - name: Create /srv/netboot
      file:
        state: directory
        path: /srv/netboot

## Set up DHCP server
    - name: Install DHCP package
      apt:
        pkg: isc-dhcp-server
        state: latest
        update_cache: true

## Config config files
    - name: fetch DHCP config file
      ansible.builtin.copy:
        src: ./files/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r

## Start and enable DHCP service
    - name: start and enable DHCP service
      ansible.builtin.systemd_service:
        state: started
        name: isc-dhcp-server
        enabled: true

## Set up TFTP server
    - name: Install the TFTP package
      apt:
        pkg: tftpd-hpa
        state: latest
        update_cache: true

    - name: fetch TFTP config
      ansible.builtin.copy:
        src: ./files/tftpd-hpa.conf
        dest: /etc/default/tftpd-hpa
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: start and enable TFTP service
        ansible.builtin.systemd_service:
          state: started
          name: tftpd-hpa
          enabled: true

## menu.ipxe / PXE menu and conf
## ??? rc-local / busybox listening on :80 on eth0 ???

## Deal with images
## Fetch shredOS image
## Mount shredOS image
## Fetch Blancco image
## Mount Blancco image
## Fetch SLAM Blancco image
## Mount SLAM Blancco image
## Fetch SystemRescueCD image
## Mount --""-- image

## Firewall rule to only allow cloud.blancco.com traffic out !!!

## Update fstab



# Setup libvirt
## Config network bridge
## Setup Windows server

# Install CTASecureWipeCerts
    - name: Install CTASecureWipeCerts dependancies
      apt:
        pkg:
          - dialog
          - python3-dialog
          - git
        state: latest
        update_cache: true

    - name: Clone WipeCertificates git repo
      git:
        repo: https://github.com/CommunityTechaid/WipeCertificates.git
        dest: $HOME/WipeCertificates
        clone: yes
        update: yes

## CTADiskHealth
    - name: Copy CTADiskHealth wrapper script to /usr/local
      become: yes
      command: 
        cmd: cp $HOME/WipeCertificates/GenerateCerts.py /usr/local/bin/CTASecureWipeCerts
    
    - name: Copy CTADiskHealth .tex template to /usr/local
      become: yes  
      command: 
        cmd: cp $HOME/WipeCertificates/CTA.tex /usr/local/bin/CTA.tex
    
    - name: Copy CTADiskHealth bash script to /usr/local
      become: yes
      command:
        cmd: cp $HOME/WipeCertificates/BashGenCerts.sh /usr/local/bin/BashGenCerts.sh
