# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  # define an extra network to get two network adapter
  config.vm.network "private_network",
     ip: "10.0.0.1",
     auto_config: false
  # Provision conf for Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "zeta-playbook.yml"
  end
end
